### ISSUE TITLE
Cannot compile plugin agains latest coredns

### ISSUE THREAD

**Issue by drc0** [c-mueller/ads#38]
```
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=f6262eb2-dirty" -o coredns
github.com/c-mueller/ads
# github.com/c-mueller/ads
/go/pkg/mod/github.com/c-mueller/ads@v0.2.2/setup.go:57:4: undefined: metrics.MustRegister
/go/pkg/mod/github.com/c-mueller/ads@v0.2.2/setup.go:58:4: undefined: metrics.MustRegister
/go/pkg/mod/github.com/c-mueller/ads@v0.2.2/setup.go:59:4: undefined: metrics.MustRegister
/go/pkg/mod/github.com/c-mueller/ads@v0.2.2/setup.go:60:4: undefined: metrics.MustRegister
make: *** [Makefile:16: coredns] Error 2
```

**Comment by c-mueller** [comment]
was this the master branch of coredns? Or version 1.7.0?

**Comment by drc0** [comment]
it was commit f6262eb2 but I don't remember if it was from git pull or go get..sorry.

**Comment by c-mueller** [comment]
> 
> 
> it was commit f6262eb2 but I don't remember if it was from git pull or go get..sorry.

Okay, i was expecting this, since it does not work for me either, I will fix it once CoreDNS 1.7.1 is released.

**Comment by c-mueller** [comment]
Version 0.2.4 should work with version 1.7.1, however `master`still fails. 

Will create a new issue to fix this.
